Lab1 Tkachik Andrey
AndreyTkachik/PDRIS_2024 pull request #1
Opened 2024-10-17 08:31 UTC by AndreyTkachik

2024-10-21 19:37 UTC, Smartslame commented on lab1/disk_monitor.sh
> +    START_TIMESTAMP=$(date +"%H-%M-%S")
на мой взгляд лишняя переменная, можно спокойно и без нее)

2024-10-21 19:37 UTC, Smartslame approved these changes

2024-10-21 19:38 UTC, Smartslame requested changes

2024-10-21 19:38 UTC, Smartslame commented on lab1/disk_monitor.sh
> +monitor_disk() {
не вижу обработки перехода границы суток

2024-10-22 11:06 UTC, AndreyTkachik commented on lab1/disk_monitor.sh
> +monitor_disk() {
```
csv_file="inode_monitoring_${current_date}_${START_TIMESTAMP}.csv"
if [ ! -f "$csv_file" ]; then
            echo "Time,Filesystem,Used Space,Available Space,Used Inodes,Free Inodes" > "$csv_file"
fi
```
После перехода через сутки поменяется current_date, а в следствии чего код, который я предоставил выше, создаст новый файл, который будет содержать следующую дату как мы начали мониторинг, а таке время, когда именно мы начали мониторинг в прошлых сутках.

2024-10-22 11:07 UTC, AndreyTkachik commented on lab1/disk_monitor.sh
> +    START_TIMESTAMP=$(date +"%H-%M-%S")
Эта переменная как раз таки нужна чтобы отслеживать время, когда был запуск нашего мониторинга

2024-10-31 16:59 UTC, Smartslame approved these changes

2024-10-31 16:59 UTC, Smartslame commented on lab1/disk_monitor.sh
> +monitor_disk() {
"таке время, когда именно мы начали мониторинг в прошлых сутках." 
это странно, ожидается видеть время создания файла, а не время первоначального запуска , но ок

2024-12-06 09:41 UTC, merged