Lab2 Tkachik Andrey
AndreyTkachik/PDRIS_2024 pull request #2
Opened 2024-11-04 13:40 UTC by AndreyTkachik

2024-11-25 17:14 UTC, Smartslame requested changes

2024-11-25 17:14 UTC, Smartslame commented on ansible_lab/Dockerfile.spring
> +COPY target/spring-boot-0.0.1-SNAPSHOT.jar app.jar
докер контейнер должен быть пустым

2024-11-25 17:14 UTC, Smartslame commented on ansible_lab/Dockerfile.spring
> +RUN apt install -y openjdk-17-jdk
и без этого

2024-11-25 17:14 UTC, Smartslame commented on ansible_lab/ansible/playbook.yml
> +      command: "java -jar /app.jar"
хочется видеть не просто запуск какого-то джарника, а установку нужных зависимостей, выкачку исходников, их сборку и запуск

2024-11-25 17:14 UTC, Smartslame commented on ansible_lab/ansible/playbook.yml
> +      command: "java -jar /app.jar"
также не вижу установку nginx либо деплой и запуск скрипта из 1 лабы

2024-11-25 17:48 UTC, AndreyTkachik commented on ansible_lab/ansible/playbook.yml
> +      command: "java -jar /app.jar"
Что подразумевается под установкой нужных зависимостей? Выкачкой исходников?

Задание начинал делать до изменений с nginx. Сейчас изменю создание контейнера и сделаю установку всех требуемых компонентов через ansible

2024-11-25 19:19 UTC, AndreyTkachik commented on ansible_lab/Dockerfile.spring
> +COPY target/spring-boot-0.0.1-SNAPSHOT.jar app.jar
Оcnавил только подгрузку Ubuntu

2024-12-04 20:11 UTC, Smartslame approved these changes

2024-12-06 09:42 UTC, merged